name: Deploy
on: [push]
jobs:
  x-kassa_deploy:
    runs-on: ubuntu-18.04
    name: Build on Ubuntu-18.04 aarch64
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: appleboy/scp-action@master
        name: Copy repository contents via scp
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "~/Express/x-kassa"

      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/Express/x-kassa
            npm install
            pm2 start app.js --watch
