name: deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build on Ubuntu-18.04 x64
    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "~/Express/x-kassa"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          script: cd ~/Express/x-kassa && pm2 start app.js --watch
