name: x-kassa
on: [push]
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "."
          target: "~/Express/x-kassa"

      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh
            bash nodesource_setup.sh
            apt install nodejs -y
            node --version
            npm --version
            rm -rf nodesource_setup.sh
            npm i -g pm2
            pm2 --version
            cd ~/Express/x-kassa
            npm install
            pm2 stop X-KASSA
            pm2 delete X-KASSA
            pm2 start app.js --name X-KASSA --watch
